---
name: Build

on: pull_request

jobs:
  build:
    uses: freezingsaddles/freezing-web/.github/workflows/build-docker.yml@1.6.0
    with:
      tag: latest-actions-build
      repo: freezing-beanstalkd
    secrets: inherit
