---
name: Build Tag

on:  # yamllint disable-line
  push:
    tags:
      - '*'

jobs:
  build:
    uses: freezingsaddles/freezing-web/.github/workflows/build-docker.yml@1.6.0
    with:
      tag: ${{ github.ref_name }}
      repo: freezing-beanstalkd
    secrets: inherit
